export default {
	idioma: 'Idioma',
	search: 'Buscar',
	reload: 'Recargar',
	new: 'Nuevo',
	usuarios_nuevo: 'Nuevo usuario',
	edit: 'Editar',
	delete: 'Eliminar',
	processing: 'Procesando...',
	delete_reg: 'Eliminar registro',
	delete_reg_confirm: '¿Está seguro que desea eliminar el registro?',
	si: 'Si',
	manage_tags: 'Gestionar etiquetas',
	manage_categories: 'Gestionar categorías',
	new_file: 'Nuevo archivo',
	new_category: 'Nueva categoría',
	edit_category: 'Editar categoría',
	new_user: 'Nuevo usuario',
	edit_user: 'Editar usuario',
	new_tag: 'Nueva etiqueta',
	edit_tag: 'Editar etiqueta',
	new_course: 'Nuevo curso',
	edit_course: 'Editar curso',
	new_sesion: 'Nueva sesión',
	edit_sesion: 'Editar sesión',
	new_post: 'Nueva noticia',
	edit_post: 'Editar noticia',
	new_lib: 'Nuevo archivo',
	edit_lib: 'Editar archivo',
	new_level: 'Nuevo nivel',
	edit_level: 'Editar nivel',
	new_exam: 'Nuevo examen',
	edit_exam: 'Editar examen',
	title: 'Título',
	content: 'Contenido',
	category: 'Categoría',
	categories: 'Categorías',
	tags: 'Etiquetas',
	file: 'Archivo',
	back: 'Volver',
	close: 'Cerrar',
	picture: 'Imagen',
	save: 'Guardar',
	cancel: 'Cancelar',
	name: 'Nombre',
	lastname: 'Apellido',
	phone: 'Teléfono',
	sex: 'Sexo',
	performance_avanzar: 'Performance para avanzar de nivel',
    performance_mantenerse: 'Performance para mantenerse en el nivel',
    fecha_noticia: 'Fecha de la noticia',
    start_sesion: 'Inicio de la sesión',
  	end_sesion: 'Fin de la sesión',
  	curso_correlativo: 'Curso correlativo',
  	type_content: 'Tipo de contenido',
  	curso: 'Curso',
  	cursos: 'Cursos',
  	examen: 'Examen',
  	examenes: 'Examenes',
  	type_source: 'Tipo de recurso',
  	link: 'Enlace',
  	rendimiento_academico: 'Rendimiento académico',
    rendimiento_empresa: 'Rendimiento en la empresa',
    prev_level: 'Nivel anterior',
    level: 'Nivel',
    peso_academico: 'Peso académico',
    peso_empresa: 'Peso empresa',
    resultado_performance: 'Resultado del performance',
    generales: 'Generales',
    company_name: 'Nombre de la compañía',
    user_eval_weight: 'Peso para rendimiento académico por defecto',
    periods: 'Periodos',
    months: 'Meses',
    actions: 'Acciones',
    filtros: 'Filtros',
    period: 'Periodo',
    rango_fechas: 'Rango de fechas',
    created_at: 'Fecha de creación',
    birthday: 'Fecha de nacimiento',
    password: 'Clave',
    forgot_password: '¿Olvidó su contraseña?',
    recovery: 'Recuperar',
    recovery_success: 'Le hemos enviado un email con los pasos a seguir.',
    aula_virtual: 'Aula virtual',
    programadas: 'Programadas',
    start: 'Inicio',
	end: 'Fin',
	enter: 'Entrar',
	not_found: 'No se encontraron resultados',
	new_aula: 'Nueva aula virtual',
	edit_aula: 'Editar aula virtual',
	delete_aula: '¿Seguro que desea eliminar el aula virtual?',
	field_required: 'El campo %(field)s es obligatorio',
	order: 'Ordenamiento',
	direction: 'Dirección',
	none: 'Ninguno',
	ascending: 'Ascendente',
	descending: 'Descendente',
	login: {
		title: 'Iniciar Sesión',
		button: 'Acceder',
		success: 'Login exitoso.'
	},
	menu: {
		dashboard: 'Tablero de comando',
		formacion: 'Formación',
		noticias: 'Noticias',
		biblioteca: 'Biblioteca',
		niveles: 'Niveles',
		segmentaciones: 'Segmentaciones',
		usuarios: 'Usuarios',
		performance: 'Performance',
		configuracion: 'Configuración'
	},
	errors: {
		connect: 'Ha ocurrido un error, compruebe su conexión a internet o contacte al administrador.'
	},
	dashboard_trans: {
		new: 'Nuevo',
		comments: 'Comentarios',
		new_: 'Nueva',
		notificar_cursos: 'Notificar cuando hayan cursos nuevos',
		notificar_nivel: 'Notificar cuando suba de nivel',
		notificar_comentarios: 'Notificar cuando alguien haya comentado su publicación',
		notificar_noticias: 'Notificar Nuevas noticias',
		mensaje_bienvenida: 'Mensaje de bienvenida',
		user_eval_weight: 'Peso para rendimiento académico por defecto',
		company_name: 'Nombre de la compañía',
		message: 'Mensaje',
		course: 'Curso',
		news: 'Noticias',
		add: 'Agregar',
		end: 'Fin',
		suscribed: 'Inscritos',
		posts: 'Publicaciones',
		score: 'Puntuación',
		performance_avanzar: 'Performance para avanzar de nivel',
		performance_mantenerse: 'Performance para mantenerse en el nivel',
		fecha_noticia: 'Fecha de la noticia',
		fecha: 'Fecha',
		rendimiento_academico: 'Rendimiento académico',
		rendimiento_empresa: 'Rendimiento en la empresa',
		prev_level: 'Nivel anterior',
		cancel: 'Cancelar',
		peso_academico: 'Peso académico',
		peso_empresa: 'Peso empresa',
		resultado_performance: 'Resultado del performance',
		subio: 'Subió',
		bajo: 'Bajó', 
		se_mantuvo: 'Se mantuvo',
		courses: 'Cursos',
		comment: 'Comentario',
		level: 'Nivel',
		levels: 'Niveles',
		start_sesion: 'Inicio de la sesión',
		end_sesion: 'Fin de la sesión',
		exam_free: 'Examen libre',
		exam: 'Examen',
		name: 'Nombre',
		correlativo_curso: 'Curso correlativo',
		external_link: 'Enlace externo',
		phone: 'Teléfono',
		select_video: 'Seleccione el video',
		porcentaje_aprobar: 'Porcentaje para aprobar',
		approved: 'Aprobado',
		cantidad_preguntas_mostrar: 'Cantidad de preguntas a mostrar',
		cantidad_respuestas_mostrar: 'Cantidad de respuestas a mostrar',
		preguntas: 'Preguntas',
		pregunta: 'Pregunta',
		valor: 'Valor',
		respuesta_correcta: 'Respuesta correcta',
		respuesta: 'Respuesta',
		respuestas: 'Respuestas',
		new_answer: 'Nueva respuesta',
		delete_question: 'Eliminar pregunta',
		add_question: 'Agregar pregunta',
		success_exam: 'Examen creado con éxito',
		success_exam_edit: 'Examen editado con éxito',
		auto_weight: 'Peso automático para las preguntas',
		picture: 'Imagen',
		last_name: 'Apellido',
		identity_card: 'Cédula',
		email: 'Correo electrónico',
		actions: 'Acciones',
		date: 'Fecha',
		cursos_aprobados: 'Cursos aprobados',
		cursos_inscritos: 'Cursos inscritos',
		cursos_presentados: 'Cursos presentados',
		presentados: 'Presentados',
		cantidad_usuarios: 'Cantidad de usuarios',
		visitas: 'Visitas en las últimas 24 horas',
		downloaded: 'Archivos descargados',
		update: 'Modificar',
		client: 'Cliente',
		delete: 'Eliminar',
		the: 'El',
		the_: 'La',
		is: 'es',
		required: 'obligatorio',
		required_: 'obligatoria',
		valid: 'Válido',
		profesion: 'Profesión',
		profesional: 'Profesional',
		bithdate: 'Fecha de nacimiento',
		sex: 'Sexo',
		male: 'Masculino',
		female: 'Femenino',
		sin_definir: 'Sin definir',
		unsuscribed: 'No inscritos',
		reproved: 'No aprobados',
		notes: 'Notas',
		categorys: 'Categorías',
		back: 'Volver',
		save: 'Guardar',
		view: 'Ver',
		views: 'Vistas',
		datas: 'datos',
		edit: 'Editar',
		user: 'Usuario',
		password: 'Contraseña',
		protocol: 'Protocolo',
		port: 'Puerto',
		proccesing: 'Procesando...',
		correo: 'Correo',
		format: 'Formato',
		formats: 'Formatos',
		asunto: 'Asunto',
		title: 'Título',
		content: 'Contenido',
		send: 'Enviar',
		destinatario: 'Destinatario(s)',
		home: 'Inicio',
		envio_correo: 'Envío de correos',
		event: 'Evento',
		status: 'Estatus',
		variables: 'Variables',
		disponibles: 'disponibles',
		tramites: 'Trámites',
		cargo: 'Cargo',
		servicios_profesional: 'Servicios que maneja el profesional',
		etapas_servicio: 'Etapas del servicio',
		description: 'Descripción',
		order: 'Orden',
		step: 'Etapa',
		steps: 'Etapas',
		active: 'Activo',
		activity: 'Actividad',
		form: 'Formulario',
		format_correo: 'Formato de correo',
		files: 'Archivos',
		generales: 'Generales',
		inicio_performance: 'Fecha de inicio para el performance',
		meses_performance: 'Duración de periodos en meses',
		months: 'Meses',
		periods: 'Periodos',
		price: 'Precio',
		tag: 'Etiqueta',
		tags: 'Etiquetas',
		link: 'Enlace',
		rank: 'Ranking empresarial',
		service: 'Servicio',
		tramites_abiertos: 'Trámites abiertos',
		tramites_totales: 'Trámites totales',
		tramites_pendientes: 'Trámites pendientes',
		tramites_terminados: 'Trámites terminados',
		anho_actual: 'Año actual',
		uploading: 'Subiendo...',
		upload: 'Subir',
		preparado_subir: 'Preparado para subir',
		download: 'Descargar',
		downloads: 'Descargas',
		finalizado: 'Finalizado',
		finalizar: 'Finalizar',
		revert: 'Revertir',
		datos_cliente: 'Datos del cliente',
		datos_servicio: 'Datos del servicio',
		fecha_inicio: 'Fecha de inicio',
		puntuacion_aprobar: 'Puntuación para aprobar',
		repeat: 'Repetir'
	}
}