export default {
	idioma: 'Language',
	search: 'Search',
	reload: 'Reload',
	new: 'New',
	usuarios_nuevo: 'New user',
	edit: 'Edit',
	delete: 'Delete',
	processing: 'Processing...',
	delete_reg: 'Delete record',
	delete_reg_confirm: 'Are you sure you want to delete the record?',
	si: 'Yes',
	manage_tags: 'Manage tags',
	manage_categories: 'Manage categories',
	new_file: 'New file',
	new_category: 'New category',
	edit_category: 'Edit category',
	new_user: 'New user',
	edit_user: 'Edit user',
	new_tag: 'New tag',
	edit_tag: 'Edit tag',
	new_course: 'New course',
	edit_course: 'Edit course',
	new_sesion: 'New session',
	edit_sesion: 'Edit session',
	new_post: 'New post',
	edit_post: 'Edit post',
	new_lib: 'New file',
	edit_lib: 'Edit file',
	new_level: 'New level',
	edit_level: 'Edit level',
	new_exam: 'New exam',
	edit_exam: 'Edit exam',
	title: 'Title',
	content: 'Content',
	category: 'Category',
	categories: 'Categories',
	tags: 'Tags',
	file: 'File',
	back: 'Back',
	close: 'Close',
	picture: 'Picture',
	save: 'Save',
	cancel: 'Cancel',
	name: 'Name',
	lastname: 'Last name',
	phone: 'Phone',
	sex: 'Sex',
	performance_avanzar: 'Performance for level up',
	performance_mantenerse: 'Performance for stay in current level',
	fecha_noticia: 'Created date',
	start_sesion: 'Session start',
    end_sesion: 'Session end',
    curso_correlativo: 'Correlative course',
    type_content: 'Type content',
    curso: 'Course',
    cursos: 'Courses',
  	examen: 'Exam',
  	examenes: 'Exams',
  	type_source: 'Type source',
  	link: 'Link',
  	rendimiento_academico: 'Academic average',
	rendimiento_empresa: 'Company average',
	prev_level: 'Previous level',
	level: 'Level',
	peso_academico: 'Academic weight',
    peso_empresa: 'Company weight',
    resultado_performance: 'Performance result',
    generales: 'Generals',
    company_name: 'Company name',
    user_eval_weight: 'Company eval weight default',
    periods: 'Periods',
    months: 'Months',
    actions: 'Actions',
    filtros: 'Filters',
    period: 'Period',
    rango_fechas: 'Date range',
    created_at: 'Created at',
    birthday: 'Birthday',
    password: 'Password',
    forgot_password: 'Forgot your password?',
    recovery: 'Recovery',
    recovery_success: 'We have sent you an email with the steps to follow.',
    aula_virtual: 'Virtual classroom',
    programadas: 'Scheduled',
    start: 'Start at',
	end: 'Finish at',
	enter: 'Enter',
	not_found: 'No results found',
	new_aula: 'New virtual classroom',
	edit_aula: 'Edit virtual classroom',
	delete_aula: 'Are you sure you want to delete the virtual classroom?',
	field_required: 'The field %(field)s is required',
	order: 'Order',
	direction: 'Direction',
	none: 'None',
	ascending: 'Ascending',
	descending: 'Descending',
	login: {
		title: 'Sign in',
		button: 'Login',
		success: 'Successful login.'
	},
	menu: {
		dashboard: 'Dashboard',
		formacion: 'Learning',
		noticias: 'News',
		biblioteca: 'Files',
		niveles: 'Levels',
		segmentaciones: 'Segmentations',
		usuarios: 'Users',
		performance: 'Performance',
		configuracion: 'Settings'
	},
	errors: {
		connect: 'An error has occurred, check your internet connection or contact the administrator.'
	},
	dashboard_trans: {
		new: 'New',
		comments: 'Comments',
		new_: 'New',
		notificar_cursos: 'Notify when has new courses',
		notificar_nivel: 'Notify when users up nivel',
		notificar_comentarios: 'Notify when somebody comment your post',
		notificar_noticias: 'Notify news',
		mensaje_bienvenida: 'Welcome message',
		user_eval_weight: 'Company eval weight default',
		company_name: 'Company name',
		mensaje: 'Message',
		course: 'Course',
		news: 'News',
		add: 'Add',
		end: 'End',
		suscribed: 'Suscribed',
		posts: 'Posts',
		score: 'Score',
		performance_avanzar: 'Performance for level up',
		performance_mantenerse: 'Performance for stay in current level',
		fecha_noticia: 'Created date',
		fecha: 'Date',
		rendimiento_academico: 'Academic average',
		rendimiento_empresa: 'Company average',
		prev_level: 'Previous level',
		cancel: 'Cancel',
		peso_academico: 'Academic weight',
		peso_empresa: 'Company weight',
		resultado_performance: 'Performance result',
		subio: 'Up',
		bajo: 'Down',
		se_mantuvo: 'Current',
		courses: 'Courses',
		comment: 'Comment',
		level: 'Level',
		levels: 'Levels',
		start_sesion: 'Session start',
		end_sesion: 'Session end',
		exam_free: 'Free exam',
		exam: 'Exam',
		name: 'Name',
		correlativo_curso: 'Heritage course',
		external_link: 'External link',
		phone: 'Phone',
		select_video: 'Select video',
		porcentaje_aprobar: 'Percent for approved',
		approved: 'Approved',
		cantidad_preguntas_mostrar: 'Questions quantity to show',
		cantidad_respuestas_mostrar: 'Answers quantity to show',
		preguntas: 'Questions',
		pregunta: 'Question',
		valor: 'Value',
		respuesta_correcta: 'Correct answer',
		respuesta: 'Answer',
		respuestas: 'Answers',
		new_answer: 'New answer',
		delete_question: 'Delete question',
		add_question: 'Add question',
		success_exam: 'Exam created successfully',
		success_exam_edit: 'Exam edited successfully',
		auto_weight: 'Automatic weight for questions',
		picture: 'Picture',
		last_name: 'Last name',
		identity_card: 'Identification card',
		email: 'Email',
		actions: 'Actions',
		date: 'Date',
		cursos_inscritos: 'Suscribed courses',
		cursos_aprobados: 'Approved courses',
		cursos_presentados: 'Presented courses',
		presentados: 'Presented',
		cantidad_usuarios: 'Users quantity',
		visitas: 'Visits in the last 24 hours',
		downloaded: 'Downloaded files',
		update: 'Update',
		client: 'Client',
		the: 'The',
		the_: 'The',
		is: 'is',
		required: 'required',
		required_: 'required',
		valid: 'Valid',
		profesion: 'Profession',
		profesional: 'Professional',
		bithdate: 'Birthdate',
		sex: 'Sex',
		male: 'Male',
		female: 'Female',
		sin_definir: 'Not defined',
		unsuscribed: 'Unsubscribed',
		reproved: 'Reproved',
		notes: 'Notes',
		back: 'Back',
		save: 'Save',
		view: 'View',
		views: 'Views',
		datas: 'data',
		edit: 'Edit',
		user: 'User',
		password: 'password',
		protocol: 'Protocol',
		port: 'Port',
		proccesing: 'Processing...',
		correo: 'Email',
		format: 'Format',
		formats: 'Formats',
		asunto: 'Subject',
		title: 'Title',
		content: 'Content',
		send: 'Send',
		destinatario: 'Addressee',
		home: 'Home',
		envio_correo: 'Sending mail',
		event: 'Event',
		status: 'Status',
		variables: 'Variables',
		disponibles: 'available',
		tramites: 'Procedures',
		cargo: 'Position',
		servicios_profesional: 'Services that the professional handles',
		etapas_servicio: 'Stages of service',
		description: 'Description', 
		delete: 'Delete',
		order: 'Order',
		step: 'Step',
		steps: 'Steps',
		generales: 'Generals',
		inicio_performance: 'Start date for performance',
		meses_performance: 'Time for performance in months',
		months: 'Months',
		periods: 'Periods',
		active: 'File',
		activity: 'Activity',
		form: 'Form',
		format_correo: 'Mail format',
		files: 'Files',
		price: 'Price',
		categorys: 'Categorys',
		tag: 'Tag',
		tags: 'Tags',
		link: 'Link',
		rank: 'Company rank',
		service: 'Service',
		tramites_abiertos: 'Open procedures',
		tramites_totales: 'Total procedures',
		tramites_pendientes: 'Pending procedures',
		tramites_terminados: 'Completed procedures',
		anho_actual: 'Current year',
		uploading: 'Uploading...',
		upload: 'Upload',
		preparado_subir: 'Ready to upload',
		download: 'Download',
		downloads: 'Downloads',
		finalizado: 'Finalized',
		finalizar: 'Finalize',
		revert: 'Revert',
		datos_cliente: 'Client data',
		datos_servicio: 'Service data',
		fecha_inicio: 'Start date',
		puntuacion_aprobar: 'Score for approved',
		repeat: 'Repeat'
	}
}